#!/usr/bin/env bash
set -euo pipefail

mode="release"
tag=""
output=""
notes_dir=".release-notes"

usage() {
  cat <<'USAGE'
Usage: render-git-cliff-notes.sh --mode release|changelog --tag vX.Y.Z --output PATH

Combines the manual release note fragment from .release-notes/<tag>.md with
the automated Changes section generated by git-cliff.
USAGE
}

die() {
  echo "error: $*" >&2
  exit 1
}

while (($#)); do
  case "$1" in
    --mode)
      mode="${2:-}"
      shift 2
      ;;
    --tag)
      tag="${2:-}"
      shift 2
      ;;
    --output|-o)
      output="${2:-}"
      shift 2
      ;;
    --notes-dir)
      notes_dir="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      usage >&2
      die "unknown argument: $1"
      ;;
  esac
done

[[ "$mode" == "release" || "$mode" == "changelog" ]] || die "--mode must be release or changelog"
[[ -n "$tag" ]] || die "--tag is required"
[[ -n "$output" ]] || die "--output is required"
[[ -d "$notes_dir" ]] || die "missing release notes directory: $notes_dir"

validate_note() {
  local file="$1"
  local failed=0

  grep -Eq '^### Summary[[:space:]]*$' "$file" || {
    echo "error: $file is missing '### Summary'" >&2
    failed=1
  }
  grep -Eq '^### Upgrade Notes[[:space:]]*$' "$file" || {
    echo "error: $file is missing '### Upgrade Notes'" >&2
    failed=1
  }
  if grep -Eq '^### Changes[[:space:]]*$' "$file"; then
    echo "error: $file must not contain '### Changes'; git-cliff generates it" >&2
    failed=1
  fi

  return "$failed"
}

required_note="$notes_dir/$tag.md"
[[ -f "$required_note" ]] || die "missing release note file: $required_note"

shopt -s nullglob
for note in "$notes_dir"/v*.md; do
  validate_note "$note"
done

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

case "$mode" in
  release)
    git-cliff --latest --strip header > "$tmp"
    ;;
  changelog)
    git-cliff > "$tmp"
    ;;
esac

awk -v notes_dir="$notes_dir" -v required_tag="$tag" '
BEGIN {
  emitted = 0
  skip_blanks_after_note = 0
}

function release_tag(version) {
  return version ~ /^v/ ? version : "v" version
}

function inject_note(tag, path, line) {
  path = notes_dir "/" tag ".md"
  if ((getline line < path) > 0) {
    print ""
    print line
    while ((getline line < path) > 0) {
      print line
    }
    close(path)
    return
  }
  close(path)

  if (tag == required_tag) {
    printf("error: required release note disappeared while rendering: %s\n", path) > "/dev/stderr"
    exit 42
  }
}

!emitted && $0 == "" {
  next
}

skip_blanks_after_note && $0 == "" {
  next
}

skip_blanks_after_note {
  print ""
  skip_blanks_after_note = 0
}

/^## \[[^]]+\]/ {
  emitted = 1
  print
  version = $0
  sub(/^## \[/, "", version)
  sub(/\].*$/, "", version)
  inject_note(release_tag(version))
  skip_blanks_after_note = 1
  next
}

{
  emitted = 1
  print
}
' "$tmp" > "$output"
